POST http://localhost:5000/api/users/ HTTP/1.1
Content-Type: application/json

{
    "firstName": "Iron",
    "lastName": "Man",
    "email": "tony@man.com",
    "password": "spider",
    "birthday": "1995-09-09",
    "gender": "male"
}